collections:
  - name: ansible.windows
    version: ">=2.2.0"

  - name: community.windows
    version: ">=3.0.0"

#  - name: chocolatey.chocolatey
#    version: ">=1.5.3"

  - name: ansible.windows
    version: ">=3.3.0"

